// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZwqAWcSin8_VQ_P3TJ0BmixtzrK-1aVw',
    appId: '1:1032090010717:web:16167f1b9b7c6f71d5b9b4',
    messagingSenderId: '1032090010717',
    projectId: 'todolistapp-1d9a2',
    authDomain: 'todolistapp-1d9a2.firebaseapp.com',
    storageBucket: 'todolistapp-1d9a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgOrWNkDTVL7nyhnPBWiiIs8a1ATslsiQ',
    appId: '1:1032090010717:ios:f43b31e9239b8d62d5b9b4',
    messagingSenderId: '1032090010717',
    projectId: 'todolistapp-1d9a2',
    storageBucket: 'todolistapp-1d9a2.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgOrWNkDTVL7nyhnPBWiiIs8a1ATslsiQ',
    appId: '1:1032090010717:ios:f43b31e9239b8d62d5b9b4',
    messagingSenderId: '1032090010717',
    projectId: 'todolistapp-1d9a2',
    storageBucket: 'todolistapp-1d9a2.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZwqAWcSin8_VQ_P3TJ0BmixtzrK-1aVw',
    appId: '1:1032090010717:web:f4aa1cd0d84eddbcd5b9b4',
    messagingSenderId: '1032090010717',
    projectId: 'todolistapp-1d9a2',
    authDomain: 'todolistapp-1d9a2.firebaseapp.com',
    storageBucket: 'todolistapp-1d9a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhs9EQOg2Re5uHqEVdPSIPAbGKVIEGLFw',
    appId: '1:1032090010717:android:50e4077aee72d280d5b9b4',
    messagingSenderId: '1032090010717',
    projectId: 'todolistapp-1d9a2',
    storageBucket: 'todolistapp-1d9a2.appspot.com',
  );
}
